// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/ptaramona/conduyt-crm-cli/internal/cli"
	"github.com/ptaramona/conduyt-crm-cli/internal/client"
	"github.com/ptaramona/conduyt-crm-cli/internal/cliutil"
	"github.com/ptaramona/conduyt-crm-cli/internal/config"
	"github.com/ptaramona/conduyt-crm-cli/internal/learn"
	"github.com/ptaramona/conduyt-crm-cli/internal/mcp/bound"
	"github.com/ptaramona/conduyt-crm-cli/internal/mcp/cobratree"
	"github.com/ptaramona/conduyt-crm-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='account'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName         string
	WireName           string
	Location           string
	BodyPath           []string
	Format             string
	RequestContentType string
	Default            string
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}
func mcpMultipartFieldValue(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	if data, err := json.Marshal(v); err == nil {
		return string(data)
	}
	return fmt.Sprintf("%v", v)
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcplib.NewToolResultError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcplib.NewToolResultError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		multipartFields := make(map[string]string)
		multipartFileFields := make(map[string]string)
		multipart := false
		// bodyJSONOverride holds an opaque body for endpoints whose request
		// schema is a oneOf/anyOf and was wired with a single body_json input.
		// When set, it replaces the bodyArgs map for POST/PUT/PATCH.
		var bodyJSONOverride json.RawMessage
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			if strings.EqualFold(binding.RequestContentType, "multipart/form-data") {
				multipart = true
			}
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
				if multipart {
					if strings.EqualFold(binding.Format, "binary") {
						multipartFileFields[binding.WireName] = fmt.Sprintf("%v", v)
					} else {
						multipartFields[binding.WireName] = mcpMultipartFieldValue(v)
					}
				}
			case "body_json":
				if s, ok := v.(string); ok && s != "" {
					var parsed any
					if err := json.Unmarshal([]byte(s), &parsed); err != nil {
						return mcplib.NewToolResultError("body_json must be a valid JSON object: " + err.Error()), nil
					}
					if _, isMap := parsed.(map[string]any); !isMap {
						return mcplib.NewToolResultError(fmt.Sprintf("body_json must be a JSON object, got JSON %T", parsed)), nil
					}
					bodyJSONOverride = json.RawMessage(s)
				}
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
				if multipart {
					multipartFields[k] = mcpMultipartFieldValue(v)
				}
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PostMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PostMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					} else {
						data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					}
					break
				}
				if readOnly {
					data, _, err = c.PostQueryWithParams(ctx, path, params, bodyJSONOverride)
				} else {
					data, _, err = c.PostWithParams(ctx, path, params, bodyJSONOverride)
				}
				break
			}
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PutMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PutMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					break
				}
				data, _, err = c.PutWithParams(ctx, path, params, bodyJSONOverride)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if multipart {
				if len(headers) > 0 {
					data, _, err = c.PatchMultipartWithParamsAndHeaders(ctx, path, params, multipartFields, multipartFileFields, headers)
					break
				}
				data, _, err = c.PatchMultipartWithParams(ctx, path, params, multipartFields, multipartFileFields)
				break
			}
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					break
				}
				data, _, err = c.PatchWithParams(ctx, path, params, bodyJSONOverride)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set it with: conduyt-crm-pp-cli auth set-token <token> or export CONDUYT_CRM_BEARER_AUTH=\"your-token-here\"" +
					"\n      See API docs: https://conduyt.app" +
					"\n      Run 'conduyt-crm-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: conduyt-crm-pp-cli auth set-token <token> or export CONDUYT_CRM_BEARER_AUTH=\"your-token-here\"" +
					"\n      See API docs: https://conduyt.app" +
					"\n      Run 'conduyt-crm-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource. Check that they have the required permissions and match the API's expected auth scheme." +
					"\n      Set it with: conduyt-crm-pp-cli auth set-token <token> or export CONDUYT_CRM_BEARER_AUTH=\"your-token-here\"" +
					"\n      See API docs: https://conduyt.app" +
					"\n      Run 'conduyt-crm-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcplib.NewToolResultError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcplib.NewToolResultError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			return mcplib.NewToolResultText(string(out)), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultText(method, data, pageConfig, mcpCursor), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcplib.NewToolResultText(bound.EndpointResponse(method, data))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcplib.NewToolResultText(bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	}))
}

func newMCPClient() (*client.Client, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, err
	}
	return newMCPClientFromConfig(cfg), nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty mcpStoreStatusKind = "empty"
	mcpStoreStatusReady mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run conduyt-crm-pp-cli sync to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run conduyt-crm-pp-cli sync before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	if len(status) == 0 {
		return mcpStoreStatusEmpty, nil
	}
	return mcpStoreStatusReady, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run conduyt-crm-pp-cli sync to populate the local SQLite store before using MCP search/sql."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	rows, err := db.DB().QueryContext(ctx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(results, cols, storeStatus))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(rows) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run sync again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(err error) string {
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='account', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "conduyt-crm",
		"description": "Full-coverage Conduyt CLI: every endpoint, plus Kloudi-grade send-safety forensics no other surface has.",
		"archetype":   "crm",
		"tool_count":  726,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion conduyt-crm-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "CONDUYT_CRM_BEARER_AUTH",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
			"docs_url": "https://conduyt.app",
		},
		"resources": []map[string]any{
			{
				"name":        "account",
				"description": "Manage account",
				"endpoints":   []string{"get-readiness"},
			},
			{
				"name":        "accounts",
				"description": "Manage accounts",
				"endpoints":   []string{"get", "post"},
				"writable":    true,
			},
			{
				"name":        "activities",
				"description": "Activity feed and logging",
				"endpoints":   []string{"create-activity", "get-id", "list"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "admin",
				"description": "Super-admin account management and impersonation",
				"endpoints":   []string{"clean-test-accounts", "clean-test-data", "impersonate", "list-accounts", "stop-impersonate", "toggle-comp"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "ai",
				"description": "AI-powered features (chat, email compose, contact enrichment)",
				"endpoints":   []string{"chat", "compose-email", "deal-insights", "enrich-contact", "get-daily-brief", "get-feed", "get-insights", "get-next-actions", "get-usage", "improve-email", "post-conversation-intelligence", "post-insights", "post-tasks", "summarize-contact"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "api-keys",
				"description": "API key management",
				"endpoints":   []string{"check", "create", "list", "revoke", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "api_search",
				"description": "Manage api search",
				"endpoints":   []string{"global-search"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "appointments",
				"description": "Appointment scheduling",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "automation-executions",
				"description": "Automation execution logs and step details",
				"endpoints":   []string{"get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "automation-executions.recover",
				"description": "Manage recover",
				"endpoints":   []string{"post-automation-executions-id"},
				"writable":    true,
			},
			{
				"name":        "automations",
				"description": "Workflow automations (native + n8n), publishing, analytics",
				"endpoints":   []string{"create", "create-from-template", "delete", "get", "get-failures", "get-failures-drilldown", "get-resolve", "get-schema", "get-step-logs", "list", "list-actions", "list-condition-fields", "list-events", "list-templates", "post-copilot", "post-import", "post-resolve", "post-validate", "test-webhook", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "automations.analytics",
				"description": "Manage analytics",
				"endpoints":   []string{"get-automation"},
			},
			{
				"name":        "automations.bulk-enroll",
				"description": "Manage bulk enroll",
				"endpoints":   []string{"automation"},
				"writable":    true,
			},
			{
				"name":        "automations.dependency-audit",
				"description": "Manage dependency audit",
				"endpoints":   []string{"get-automations-id"},
			},
			{
				"name":        "automations.dry-run",
				"description": "Manage dry run",
				"endpoints":   []string{"automation"},
				"writable":    true,
			},
			{
				"name":        "automations.node-stats",
				"description": "Manage node stats",
				"endpoints":   []string{"get-automation"},
			},
			{
				"name":        "automations.preflight",
				"description": "Manage preflight",
				"endpoints":   []string{"get-automations-id"},
			},
			{
				"name":        "automations.publish",
				"description": "Manage publish",
				"endpoints":   []string{"automation"},
				"writable":    true,
			},
			{
				"name":        "automations.step-logs",
				"description": "Manage step logs",
				"endpoints":   []string{"get-automation"},
			},
			{
				"name":        "automations.test-node",
				"description": "Manage test node",
				"endpoints":   []string{"post-automations-id"},
				"writable":    true,
			},
			{
				"name":        "automations.versions",
				"description": "Manage versions",
				"endpoints":   []string{"get-automations-id", "post-automations-id-id-restore"},
				"writable":    true,
			},
			{
				"name":        "availability",
				"description": "Manage availability",
				"endpoints":   []string{"get", "set"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "batch-operations",
				"description": "Manage batch operations",
				"endpoints":   []string{"get", "get-id", "post"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "batch-operations.cancel",
				"description": "Manage cancel",
				"endpoints":   []string{"post-batch-operations-id"},
				"writable":    true,
			},
			{
				"name":        "billing",
				"description": "Stripe billing, checkout, and subscription status",
				"endpoints":   []string{"create-checkout-session", "create-portal", "delete-addons", "get-addons", "get-gate", "get-status", "patch-addons", "post-addons", "webhook-stripe"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "booking-pages",
				"description": "Public booking pages (Calendly-style)",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "booking-pages.analytics",
				"description": "Manage analytics",
				"endpoints":   []string{"get-booking-pages-id"},
			},
			{
				"name":        "booking-pages.availability",
				"description": "Manage availability",
				"endpoints":   []string{"get-booking-page"},
			},
			{
				"name":        "booking-pages.embed-code",
				"description": "Manage embed code",
				"endpoints":   []string{"get-booking-pages-id"},
			},
			{
				"name":        "booking-pages.overrides",
				"description": "Manage overrides",
				"endpoints":   []string{"delete-booking-pages-id", "get-booking-pages-id", "post-booking-pages-id"},
				"writable":    true,
			},
			{
				"name":        "booking-pages.readiness",
				"description": "Manage readiness",
				"endpoints":   []string{"get-booking-pages-id"},
			},
			{
				"name":        "booking-pages.waitlist",
				"description": "Manage waitlist",
				"endpoints":   []string{"get-booking-pages-id", "patch-booking-pages-id"},
				"writable":    true,
			},
			{
				"name":        "booking-routing-forms",
				"description": "Manage booking routing forms",
				"endpoints":   []string{"delete-id", "get", "get-id", "patch-id", "post"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "bulk",
				"description": "Manage bulk",
				"endpoints":   []string{"delete-contacts", "edit-contacts", "edit-deals", "get-status", "post-contacts-dnc", "post-contacts-untag", "tag-contacts", "update-contacts", "update-deals"},
				"writable":    true,
			},
			{
				"name":        "bulk-operations",
				"description": "Bulk update, delete, and tag contacts and deals",
				"endpoints":   []string{"get-unified"},
			},
			{
				"name":        "calendar",
				"description": "Internal calendar and appointment management",
				"endpoints":   []string{"connect-google", "connect-microsoft", "create-event", "delete-connection", "delete-event", "get-connection", "get-event", "get-health", "google-callback", "list-connections", "list-events", "microsoft-callback", "sync", "update-event", "webhook-google", "webhook-microsoft"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "calendars",
				"description": "Internal calendar and appointment management",
				"endpoints":   []string{"create", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "calendars.appointments",
				"description": "Appointment scheduling",
				"endpoints":   []string{"create-calendar", "delete-calendar", "get-calendar", "list-calendar", "update-calendar"},
				"writable":    true,
			},
			{
				"name":        "calls",
				"description": "Call log management",
				"endpoints":   []string{"create-record", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "chat",
				"description": "Internal team chat channels and messages",
				"endpoints":   []string{"add-member", "add-reaction", "create-channel", "delete-message", "edit-message", "get-channels-id-upload", "get-message", "get-typing-status", "list-channels", "list-messages", "remove-member", "remove-reaction", "send-message", "send-typing-indicator", "upload-file"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "companies",
				"description": "Company (organization) management",
				"endpoints":   []string{"create-company", "delete-company", "get-company", "get-duplicates", "get-export", "get-reporting", "list", "post-merge", "update-company"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "companies.intelligence",
				"description": "Manage intelligence",
				"endpoints":   []string{"get-companies-id"},
			},
			{
				"name":        "companies.tags",
				"description": "Tag management and merging",
				"endpoints":   []string{"delete-companies-id", "delete-companies-id-id", "get-companies-id", "post-companies-id"},
				"writable":    true,
			},
			{
				"name":        "companies.timeline",
				"description": "Manage timeline",
				"endpoints":   []string{"get-companies-id"},
			},
			{
				"name":        "conduyt-auth",
				"description": "Manage conduyt auth",
				"endpoints":   []string{"accept-invite", "change-password", "delete-sessions", "forgot-password", "get-google", "get-google-callback", "get-login-history", "get-me", "get-mfa-setup", "get-microsoft", "get-microsoft-callback", "get-saml-account-slug", "get-saml-account-slug-metadata", "get-sandbox-key", "get-security-center", "get-sessions", "login", "logout", "patch-security-center", "post-mfa-challenge", "post-mfa-disable", "post-mfa-setup", "post-mfa-verify", "post-saml-account-slug-acs", "post-sandbox-key", "register", "reset-password", "switch-account"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "confirm",
				"description": "Manage confirm",
				"endpoints":   []string{"post", "put"},
				"writable":    true,
			},
			{
				"name":        "contact",
				"description": "Contact management, tagging, scoring, import/export, merge, duplicates",
				"endpoints":   []string{"upsert"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "contacts",
				"description": "Contact management, tagging, scoring, import/export, merge, duplicates",
				"endpoints":   []string{"create", "delete", "export", "find-duplicate", "get", "get-dnc-status", "get-geo", "get-import-template", "get-sources", "import", "list", "merge", "post-ai-import", "post-dry-run", "post-verify-line-type", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "contacts.active-enrollments",
				"description": "Manage active enrollments",
				"endpoints":   []string{"get-contacts-id"},
			},
			{
				"name":        "contacts.best-time",
				"description": "Manage best time",
				"endpoints":   []string{"get-contacts-id"},
			},
			{
				"name":        "contacts.collaborators",
				"description": "Manage collaborators",
				"endpoints":   []string{"delete-contacts-id", "get-contacts-id", "post-contacts-id"},
				"writable":    true,
			},
			{
				"name":        "contacts.dnc",
				"description": "Manage dnc",
				"endpoints":   []string{"get-contacts-id"},
			},
			{
				"name":        "contacts.enrich",
				"description": "Manage enrich",
				"endpoints":   []string{"post-contacts-id"},
				"writable":    true,
			},
			{
				"name":        "contacts.gdpr-export",
				"description": "Manage gdpr export",
				"endpoints":   []string{"get-contacts-id"},
			},
			{
				"name":        "contacts.gdpr-forget",
				"description": "Manage gdpr forget",
				"endpoints":   []string{"post-contacts-id"},
				"writable":    true,
			},
			{
				"name":        "contacts.score",
				"description": "Manage score",
				"endpoints":   []string{"get-contact"},
			},
			{
				"name":        "contacts.tags",
				"description": "Tag management and merging",
				"endpoints":   []string{"add-contact", "delete-contacts-id", "get-contacts-id", "remove-contact"},
				"writable":    true,
			},
			{
				"name":        "contacts.timeline",
				"description": "Manage timeline",
				"endpoints":   []string{"get-contacts-id"},
			},
			{
				"name":        "conversations",
				"description": "Threaded conversation view per contact",
				"endpoints":   []string{"get", "get-export", "get-metrics", "list", "patch-contact-id"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "conversations.compliance",
				"description": "Manage compliance",
				"endpoints":   []string{"get-conversations-contact-id"},
			},
			{
				"name":        "conversations.state",
				"description": "Manage state",
				"endpoints":   []string{"get-conversations-contact-id", "patch-conversations-contact-id"},
				"writable":    true,
			},
			{
				"name":        "custom-fields",
				"description": "Custom field definitions for contacts and deals",
				"endpoints":   []string{"create", "delete", "get-id", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "custom-fields.history",
				"description": "Manage history",
				"endpoints":   []string{"get-custom-fields-id"},
			},
			{
				"name":        "custom-fields.impact",
				"description": "Manage impact",
				"endpoints":   []string{"get-custom-fields-id"},
			},
			{
				"name":        "dashboard",
				"description": "Dashboard summary metrics",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "data-model",
				"description": "Manage data model",
				"endpoints":   []string{"get-quality"},
			},
			{
				"name":        "deals",
				"description": "Deal/opportunity management within pipelines",
				"endpoints":   []string{"create", "delete", "delete-views-id", "get", "get-export", "get-forecast", "get-inspection", "get-views", "get-views-id", "list", "patch-views-id", "post-probabilities", "post-views", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "deals.activities",
				"description": "Activity feed and logging",
				"endpoints":   []string{"get-deals-id"},
			},
			{
				"name":        "deals.contacts",
				"description": "Contact management, tagging, scoring, import/export, merge, duplicates",
				"endpoints":   []string{"delete-deals-id-id", "get-deals-id", "patch-deals-id-id", "post-deals-id"},
				"writable":    true,
			},
			{
				"name":        "deals.history",
				"description": "Manage history",
				"endpoints":   []string{"get-deals-id"},
			},
			{
				"name":        "deals.tags",
				"description": "Tag management and merging",
				"endpoints":   []string{"delete-deals-id-id", "post-deals-id"},
				"writable":    true,
			},
			{
				"name":        "deals.tasks",
				"description": "Task management with assignment and due dates",
				"endpoints":   []string{"get-deals-id", "post-deals-id"},
				"writable":    true,
			},
			{
				"name":        "dialer",
				"description": "Click-to-call dialer via Twilio",
				"endpoints":   []string{"delete-call-id-supervise", "get-agents-status", "get-call-id-media", "get-calls", "get-calls-hourly", "get-capabilities", "get-dispositions", "get-health", "get-history", "get-inbound-lookup", "get-intelligence", "get-leaderboard", "get-live-monitor", "get-queue", "get-recordings", "get-settings", "get-setup", "get-stats", "get-status-log", "get-status-log-team", "get-token", "initiate-call", "patch-call-id", "patch-settings", "post-call-eligibility", "post-call-id-ai-disposition", "post-call-id-hangup", "post-call-id-hold", "post-call-id-mute", "post-call-id-record", "post-call-id-supervise", "post-call-id-transfer", "post-call-id-vm-drop", "post-conference-events", "post-heartbeat", "post-mirror-token", "post-queue-next", "post-queue-skip", "post-setup-wire-inbound", "post-status-log", "post-status-log-rollup"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "dnc",
				"description": "Manage dnc",
				"endpoints":   []string{"delete-id", "get", "post", "post-import"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "document-templates",
				"description": "Proposal and contract templates with merge fields",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "drip-campaigns",
				"description": "SMS drip campaign engine",
				"endpoints":   []string{"create", "delete", "get-id", "list", "seed", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "drip-enrollments",
				"description": "Manage drip enrollments",
				"endpoints":   []string{"list", "post-batch-pause", "post-batch-resume", "post-batch-stop"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "drip-enrollments.timeline",
				"description": "Manage timeline",
				"endpoints":   []string{"get-drip-enrollments-id"},
			},
			{
				"name":        "drip-tracks",
				"description": "Manage drip tracks",
				"endpoints":   []string{"delete-id", "get", "get-id", "patch-id", "post", "post-import-steps"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "email",
				"description": "Send individual and bulk emails",
				"endpoints":   []string{"send", "send-bulk"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "email-domains",
				"description": "Custom email domain verification (Resend)",
				"endpoints":   []string{"add", "get", "get-status", "remove", "update", "verify"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "emails",
				"description": "Send individual and bulk emails",
				"endpoints":   []string{"create-sequence", "create-template", "delete-template", "enroll-in-sequence", "get-health", "get-sequence", "get-sequence-stats", "get-template", "get-templates-id-usage", "list", "list-sequence-enrollments", "list-sequences", "list-templates", "post-sequences-id-preflight", "test-send-template", "unenroll-from-sequence", "update-sequence", "update-template"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "errors",
				"description": "Manage errors",
				"endpoints":   []string{"post-log"},
				"writable":    true,
			},
			{
				"name":        "files",
				"description": "File uploads and attachments",
				"endpoints":   []string{"create-record", "delete", "list", "upload"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "files.download",
				"description": "Manage download",
				"endpoints":   []string{"get-files-id"},
			},
			{
				"name":        "forms",
				"description": "Lead capture forms and submissions",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "forms.analytics",
				"description": "Manage analytics",
				"endpoints":   []string{"get-forms-id"},
			},
			{
				"name":        "forms.install-check",
				"description": "Manage install check",
				"endpoints":   []string{"post-forms-id"},
				"writable":    true,
			},
			{
				"name":        "forms.submissions",
				"description": "Manage submissions",
				"endpoints":   []string{"list-form"},
			},
			{
				"name":        "forms.submit",
				"description": "Manage submit",
				"endpoints":   []string{"form", "options-forms-id"},
				"writable":    true,
			},
			{
				"name":        "generated-documents",
				"description": "Manage generated documents",
				"endpoints":   []string{"delete-id", "get", "get-id", "patch-id", "post"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "generated-documents.download",
				"description": "Manage download",
				"endpoints":   []string{"get-generated-documents-id"},
			},
			{
				"name":        "generated-documents.send",
				"description": "Manage send",
				"endpoints":   []string{"post-generated-documents-id"},
				"writable":    true,
			},
			{
				"name":        "groups",
				"description": "Manage groups",
				"endpoints":   []string{"delete-id", "get", "patch-id", "post"},
				"writable":    true,
			},
			{
				"name":        "health",
				"description": "Manage health",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "imports",
				"description": "CSV import jobs with mapping and deduplication",
				"endpoints":   []string{"create", "get", "get-users", "list", "post-preflight", "upload-file"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "imports.download",
				"description": "Manage download",
				"endpoints":   []string{"get-imports-id"},
			},
			{
				"name":        "imports.integrity",
				"description": "Manage integrity",
				"endpoints":   []string{"get-imports-id"},
			},
			{
				"name":        "imports.launch-monitor",
				"description": "Manage launch monitor",
				"endpoints":   []string{"get-imports-id", "post-imports-id"},
				"writable":    true,
			},
			{
				"name":        "imports.process",
				"description": "Manage process",
				"endpoints":   []string{"import"},
				"writable":    true,
			},
			{
				"name":        "imports.repair",
				"description": "Manage repair",
				"endpoints":   []string{"post-imports-id"},
				"writable":    true,
			},
			{
				"name":        "imports.resubmit",
				"description": "Manage resubmit",
				"endpoints":   []string{"post-imports-id"},
				"writable":    true,
			},
			{
				"name":        "imports.resume",
				"description": "Manage resume",
				"endpoints":   []string{"post-imports-id"},
				"writable":    true,
			},
			{
				"name":        "imports.revert-preview",
				"description": "Manage revert preview",
				"endpoints":   []string{"get-imports-id"},
			},
			{
				"name":        "imports.rows",
				"description": "Manage rows",
				"endpoints":   []string{"get-imports-id", "get-imports-id-download"},
			},
			{
				"name":        "imports.side-effects",
				"description": "Manage side effects",
				"endpoints":   []string{"get-imports-id", "post-imports-id"},
				"writable":    true,
			},
			{
				"name":        "imports.stats",
				"description": "Manage stats",
				"endpoints":   []string{"get-imports-id"},
			},
			{
				"name":        "integrations",
				"description": "Third-party integrations (Zapier, etc.)",
				"endpoints":   []string{"connect", "create-zapier-subscription", "delete-zapier-subscription", "disconnect", "get-health", "get-slack-channels", "get-slack-oauth-callback", "get-slack-oauth-install", "get-zapier-sample-data", "list", "list-zapier-subscriptions", "post-slack-settings", "post-slack-test"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "invoices",
				"description": "Invoice creation, sending, payments, PDF generation",
				"endpoints":   []string{"create", "delete", "get", "get-next-number", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "invoices.payment-link",
				"description": "Manage payment link",
				"endpoints":   []string{"create-invoice"},
				"writable":    true,
			},
			{
				"name":        "invoices.payments",
				"description": "Manage payments",
				"endpoints":   []string{"list-invoice", "record-invoice"},
				"writable":    true,
			},
			{
				"name":        "invoices.pdf",
				"description": "Manage pdf",
				"endpoints":   []string{"get-invoice"},
			},
			{
				"name":        "invoices.send",
				"description": "Manage send",
				"endpoints":   []string{"invoice"},
				"writable":    true,
			},
			{
				"name":        "invoices.void",
				"description": "Manage void",
				"endpoints":   []string{"invoice"},
				"writable":    true,
			},
			{
				"name":        "knowledge",
				"description": "Manage knowledge",
				"endpoints":   []string{"delete-sources-id", "get-sources", "post-sources", "post-sources-id-reindex"},
				"writable":    true,
			},
			{
				"name":        "lead-pool",
				"description": "Manage lead pool",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "lead-pool.pull",
				"description": "Manage pull",
				"endpoints":   []string{"post-lead-pool-contact-id"},
				"writable":    true,
			},
			{
				"name":        "lead-routing",
				"description": "Lead assignment routing rules and assignment history",
				"endpoints":   []string{"create-rule", "delete-rule", "get-rule", "list-lead-assignment-log", "list-rules", "reorder-rules", "test", "update-rule"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "mailbox",
				"description": "Manage mailbox",
				"endpoints":   []string{"delete-connections-id", "get-callback-microsoft", "get-connections", "post-connect-microsoft", "post-webhooks-microsoft"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "messages",
				"description": "SMS and email message history",
				"endpoints":   []string{"create", "get-sms", "list", "send-sms"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "notes",
				"description": "Notes attached to contacts or deals",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "notifications",
				"description": "In-app notifications",
				"endpoints":   []string{"apply-profile", "create", "get-digest-settings", "list", "list-profiles", "mark-all-read", "mark-read", "replace-profiles", "update-digest-settings"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "phone-numbers",
				"description": "Manage phone numbers",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "pipelines",
				"description": "Sales pipeline and stage management",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "pipelines.stages",
				"description": "Manage stages",
				"endpoints":   []string{"create-pipeline", "delete-pipeline", "get-pipelines-id-id", "list-pipeline", "update-pipeline"},
				"writable":    true,
			},
			{
				"name":        "playbook-enrollments",
				"description": "Manage playbook enrollments",
				"endpoints":   []string{"get", "get-id", "post", "post-id"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "playbooks",
				"description": "Manage playbooks",
				"endpoints":   []string{"delete-id", "get", "get-id", "patch-id", "post"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "products",
				"description": "Product catalog for invoices",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "public",
				"description": "Unauthenticated public endpoints (booking, form submit)",
				"endpoints":   []string{"book-appointment", "get-booking-page", "get-booking-routing-slug", "get-booking-slots", "get-booking-slug-embed", "get-booking-slug-embed-badge", "get-booking-slug-embed-popup", "get-booking-slug-frame-policy", "get-booking-slug-ical", "get-branding-account-id-icon", "get-screen-share-code", "options-booking-slug", "options-booking-slug-slots", "post-booking-routing-slug", "post-booking-slug-waitlist", "post-contact", "post-screen-share-code", "post-subscribe"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "push",
				"description": "Manage push",
				"endpoints":   []string{"get-public-key", "subscribe", "unsubscribe"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "quick-connects",
				"description": "Manage quick connects",
				"endpoints":   []string{"delete-id", "get", "patch-id", "post"},
				"writable":    true,
			},
			{
				"name":        "quick-notes",
				"description": "Manage quick notes",
				"endpoints":   []string{"delete-id", "get", "patch-id", "post"},
				"writable":    true,
			},
			{
				"name":        "remote-assist",
				"description": "Manage remote assist",
				"endpoints":   []string{"post-end", "post-start"},
				"writable":    true,
			},
			{
				"name":        "rep-shifts",
				"description": "Manage rep shifts",
				"endpoints":   []string{"delete-id", "get", "patch-id", "post"},
				"writable":    true,
			},
			{
				"name":        "reporting",
				"description": "Manage reporting",
				"endpoints":   []string{"get-email", "get-pipeline", "get-sms"},
			},
			{
				"name":        "reports",
				"description": "Pipeline, revenue, activity, team, and custom reports",
				"endpoints":   []string{"create-custom", "delete-custom", "get-activity", "get-bda", "get-calls", "get-custom", "get-dialer-agent-hourly", "get-dialer-awards", "get-dialer-dispositions", "get-dialer-list-performance", "get-email-providers", "get-email-templates", "get-pipeline", "get-revenue", "get-sms-delivery", "get-sms-templates", "get-team", "list-custom", "post-custom-id-export", "post-custom-preview", "run-custom", "update-custom"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "saved-filters",
				"description": "Manage saved filters",
				"endpoints":   []string{"delete-id", "get", "patch-id", "post"},
				"writable":    true,
			},
			{
				"name":        "schema",
				"description": "Manage schema",
				"endpoints":   []string{"get-api-catalog", "get-public"},
			},
			{
				"name":        "scim",
				"description": "Manage scim",
				"endpoints":   []string{"delete-v2-users-id", "get-v2-users", "get-v2-users-id", "patch-v2-users-id", "post-v2-users", "put-v2-users-id"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "scoring-rules",
				"description": "Lead scoring rule management",
				"endpoints":   []string{"create", "delete", "list", "recalculate-scores", "simulate", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "screen-share",
				"description": "Manage screen share",
				"endpoints":   []string{"delete-session-code", "get-seats", "post-seats", "post-session"},
				"writable":    true,
			},
			{
				"name":        "settings",
				"description": "Account settings, branding, SMS/Twilio configuration",
				"endpoints":   []string{"delete-ai-byo", "delete-warmy", "get", "get-ai", "get-branding", "get-delivery-guard", "get-dormancy", "get-lead-visibility", "get-sms", "get-twilio", "get-warmy", "get-warmy-engine", "patch-ai", "patch-delivery-guard", "patch-dormancy", "patch-lead-visibility", "patch-warmy-engine", "put-ai-byo", "put-warmy", "test-integration", "test-sms", "test-twilio", "update", "update-branding", "update-sms", "update-twilio"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "smart-lists",
				"description": "Static contact lists",
				"endpoints":   []string{"create", "delete-id", "get-id", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "smart-lists.contacts",
				"description": "Contact management, tagging, scoring, import/export, merge, duplicates",
				"endpoints":   []string{"delete-smart-lists-id", "post-smart-lists-id"},
				"writable":    true,
			},
			{
				"name":        "smart-views",
				"description": "Manage smart views",
				"endpoints":   []string{"delete-id", "list", "patch-id", "patch-reorder", "post"},
				"syncable":    true,
				"writable":    true,
			},
			{
				"name":        "sms",
				"description": "Manage sms",
				"endpoints":   []string{"get-send-logs", "post-send-logs"},
				"writable":    true,
			},
			{
				"name":        "sms-providers",
				"description": "Manage sms providers",
				"endpoints":   []string{"delete-id", "get", "get-health", "get-id", "patch-id", "post"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "sms-providers.test",
				"description": "Manage test",
				"endpoints":   []string{"post-sms-providers-id"},
				"writable":    true,
			},
			{
				"name":        "sso",
				"description": "Manage sso",
				"endpoints":   []string{"delete-scim-tokens-id", "get-connection", "get-scim-tokens", "post-scim-tokens", "put-connection"},
				"writable":    true,
			},
			{
				"name":        "status-metadata",
				"description": "Manage status metadata",
				"endpoints":   []string{"delete-id", "get", "get-buckets", "get-by-stage-stage-id", "get-decisions", "get-id", "patch-id", "post", "post-dry-run", "post-import"},
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tags",
				"description": "Tag management and merging",
				"endpoints":   []string{"create", "delete", "get-id", "list", "merge", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "tasks",
				"description": "Task management with assignment and due dates",
				"endpoints":   []string{"create", "delete", "get", "get-assignment-rules", "get-open-deal-ids", "get-queues", "get-recurring", "get-sla-rules", "get-workload", "list", "put-assignment-rules", "put-queues", "put-recurring", "put-sla-rules", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "team",
				"description": "Manage team",
				"endpoints":   []string{"get-members"},
			},
			{
				"name":        "up-for-grabs",
				"description": "Manage up for grabs",
				"endpoints":   []string{"get"},
			},
			{
				"name":        "up-for-grabs.claim",
				"description": "Manage claim",
				"endpoints":   []string{"post-up-for-grabs-contact-id"},
				"writable":    true,
			},
			{
				"name":        "users",
				"description": "Team member management and invitations",
				"endpoints":   []string{"get", "get-me", "invite", "list", "patch-me", "post", "remove", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "users.avatar",
				"description": "Manage avatar",
				"endpoints":   []string{"delete-users-id", "post-users-id"},
				"writable":    true,
			},
			{
				"name":        "users.deactivate",
				"description": "Manage deactivate",
				"endpoints":   []string{"post-users-id"},
				"writable":    true,
			},
			{
				"name":        "users.invite",
				"description": "Manage invite",
				"endpoints":   []string{"post-users-id-cancel", "post-users-id-resend"},
				"writable":    true,
			},
			{
				"name":        "users.notifications",
				"description": "In-app notifications",
				"endpoints":   []string{"get-user-preferences", "update-user-preferences"},
				"writable":    true,
			},
			{
				"name":        "users.reactivate",
				"description": "Manage reactivate",
				"endpoints":   []string{"post-users-id"},
				"writable":    true,
			},
			{
				"name":        "users.reset-password",
				"description": "Manage reset password",
				"endpoints":   []string{"post-users-id"},
				"writable":    true,
			},
			{
				"name":        "users.stats",
				"description": "Manage stats",
				"endpoints":   []string{"get-users-id"},
			},
			{
				"name":        "warmy-engine",
				"description": "Manage warmy engine",
				"endpoints":   []string{"get-health", "post-sync", "post-templates"},
				"writable":    true,
			},
			{
				"name":        "webhook-logs",
				"description": "Manage webhook logs",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
			{
				"name":        "webhooks",
				"description": "Outbound webhook management and logs",
				"endpoints":   []string{"create", "create-legacy", "delete", "get", "inbound-contact", "inbound-deal", "list", "list-deliveries", "list-endpoints", "list-replay-deliveries", "messages", "replay", "sms-inbound", "sms-status", "stripe-invoice", "test", "update", "voice-inbound", "voice-recording", "voice-status", "voice-voicemail"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "workflows",
				"description": "Simple trigger-action workflows",
				"endpoints":   []string{"create", "delete", "get", "list", "update"},
				"syncable":    true,
				"searchable":  true,
				"writable":    true,
			},
			{
				"name":        "workflows.activate",
				"description": "Manage activate",
				"endpoints":   []string{"workflow"},
				"writable":    true,
			},
			{
				"name":        "workflows.deactivate",
				"description": "Manage deactivate",
				"endpoints":   []string{"workflow"},
				"writable":    true,
			},
			{
				"name":        "workflows.runs",
				"description": "Manage runs",
				"endpoints":   []string{"get-workflow", "list-workflow"},
			},
			{
				"name":        "workflows.test",
				"description": "Manage test",
				"endpoints":   []string{"workflow"},
				"writable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page parameter for subsequent pages.",
			"Control page size with the per_page parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Send-safety check", "command": "send-check", "description": "Go/no-go verdict on a list, tag, or contact before any SMS or drip: phone present, Twilio-verified line type, Twilio validity, and DNC status in one table (see imports blame for provider rejections).", "rationale": "Requires joining local contacts, DNC records, and delivery outcomes — no single API call returns the composite verdict.", "via": "mcp-command-mirror"},
			{"name": "Import delivery blame", "command": "imports blame", "description": "For one import job: who got the SMS, who was skipped, and why — grouped by rejection or skip reason.", "rationale": "Joins import rows, contacts, and SMS delivery outcomes in local SQLite; the app shows each piece on a different screen.", "via": "mcp-command-mirror"},
			{"name": "Import watcher", "command": "imports watch", "description": "Polls an import job to completion, then renders the row-outcome recap (created/updated/skipped/errors) and, with --verify, the SMS delivery report.", "rationale": "Chains job polling, preflight warnings, and the delivery report into one cron-safe command.", "via": "mcp-command-mirror"},
			{"name": "Verification cost estimate", "command": "contacts verify-line-type", "description": "Counts unverified contacts and prints the tenant-paid Twilio cost before the loop (--estimate), then drives the batched verification to done. Requires the account's Phone Line-Type Verification setting (403 'not enabled' otherwise).", "rationale": "Local pre-count over synced contacts; the API cannot answer it without paging the whole tenant.", "via": "mcp-command-mirror"},
			{"name": "Drip ledger audit", "command": "drips audit", "description": "Flags duplicate sends in a window: any contact who received the same message body more than once, from the local store.", "rationale": "Mechanically enforces the at-most-once SMS protocol via a local cross-table join.", "via": "mcp-command-mirror"},
			{"name": "Local analytics", "command": "analytics", "description": "GROUP BY over synced entities — segment counts without paging the API (--type/--group-by/--limit).", "rationale": "200k contacts behind 30-60/min rate limits make API-side aggregation impractical; the local store answers instantly.", "via": "mcp-command-mirror"},
			{"name": "Live event follow", "command": "tail", "description": "Interval polling over a resource that re-emits current results as JSON — watch messages or activities as a blast goes out.", "rationale": "Incremental polling with cursor state; a one-shot GET cannot stream deltas.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Send-safety check", "insight": "Requires joining local contacts, DNC records, and delivery outcomes — no single API call returns the composite verdict."},
			{"topic": "Import delivery blame", "insight": "Joins import rows, contacts, and SMS delivery outcomes in local SQLite; the app shows each piece on a different screen."},
			{"topic": "Import watcher", "insight": "Chains job polling, preflight warnings, and the delivery report into one cron-safe command."},
			{"topic": "Verification cost estimate", "insight": "Local pre-count over synced contacts; the API cannot answer it without paging the whole tenant."},
			{"topic": "Drip ledger audit", "insight": "Mechanically enforces the at-most-once SMS protocol via a local cross-table join."},
			{"topic": "Local analytics", "insight": "200k contacts behind 30-60/min rate limits make API-side aggregation impractical; the local store answers instantly."},
			{"topic": "Live event follow", "insight": "Incremental polling with cursor state; a one-shot GET cannot stream deltas."},
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
