// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newActivitiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "activities",
		Short:       "Activity feed and logging",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newActivitiesCreateActivityCmd(flags))
	cmd.AddCommand(newActivitiesGetIdCmd(flags))
	cmd.AddCommand(newActivitiesListCmd(flags))
	return cmd
}
