// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAiCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "ai",
		Short:       "AI-powered features (chat, email compose, contact enrichment)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAiChatCmd(flags))
	cmd.AddCommand(newAiComposeEmailCmd(flags))
	cmd.AddCommand(newAiDealInsightsCmd(flags))
	cmd.AddCommand(newAiEnrichContactCmd(flags))
	cmd.AddCommand(newAiGetDailyBriefCmd(flags))
	cmd.AddCommand(newAiGetFeedCmd(flags))
	cmd.AddCommand(newAiGetInsightsCmd(flags))
	cmd.AddCommand(newAiGetNextActionsCmd(flags))
	cmd.AddCommand(newAiGetUsageCmd(flags))
	cmd.AddCommand(newAiImproveEmailCmd(flags))
	cmd.AddCommand(newAiPostConversationIntelligenceCmd(flags))
	cmd.AddCommand(newAiPostInsightsCmd(flags))
	cmd.AddCommand(newAiPostTasksCmd(flags))
	cmd.AddCommand(newAiSummarizeContactCmd(flags))
	return cmd
}
