// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAutomationsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyActions string
	var bodyCooldownDays int
	var bodyDescription string
	var bodyExecutionTimezone string
	var bodyExecutionWindowEnd int
	var bodyExecutionWindowStart int
	var bodyGraphVersion int
	var bodyIsActive bool
	var bodyKind string
	var bodyN8nWebhookUrl string
	var bodyN8nWorkflowId string
	var bodyName string
	var bodyReenrollmentRule string
	var bodySchedule string
	var bodyScheduleTimezone string
	var bodyStopOnResponse bool
	var bodyTriggerConditions string
	var bodyTriggerEvent string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <id>",
		Short:       "Update an automation",
		Example:     "  conduyt-crm-pp-cli automations update 550e8400-e29b-41d4-a716-446655440000 --name example-resource",
		Annotations: map[string]string{"pp:endpoint": "automations.update", "pp:method": "PATCH", "pp:path": "/automations/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("trigger-event") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "trigger-event")
				}
			}
			path := "/automations/{id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if bodyActions != "" {
					bodyMap["actions"] = bodyActions
				}
				if bodyCooldownDays != 0 {
					bodyMap["cooldownDays"] = bodyCooldownDays
				}
				if bodyDescription != "" {
					bodyMap["description"] = bodyDescription
				}
				if bodyExecutionTimezone != "" {
					bodyMap["executionTimezone"] = bodyExecutionTimezone
				}
				if bodyExecutionWindowEnd != 0 {
					bodyMap["executionWindowEnd"] = bodyExecutionWindowEnd
				}
				if bodyExecutionWindowStart != 0 {
					bodyMap["executionWindowStart"] = bodyExecutionWindowStart
				}
				if bodyGraphVersion != 0 {
					bodyMap["graphVersion"] = bodyGraphVersion
				}
				if cmd.Flags().Changed("is-active") {
					bodyMap["isActive"] = bodyIsActive
				}
				if bodyKind != "" {
					bodyMap["kind"] = bodyKind
				}
				if bodyN8nWebhookUrl != "" {
					bodyMap["n8nWebhookUrl"] = bodyN8nWebhookUrl
				}
				if bodyN8nWorkflowId != "" {
					bodyMap["n8nWorkflowId"] = bodyN8nWorkflowId
				}
				if bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if bodyReenrollmentRule != "" {
					bodyMap["reenrollmentRule"] = bodyReenrollmentRule
				}
				if bodySchedule != "" {
					bodyMap["schedule"] = bodySchedule
				}
				if bodyScheduleTimezone != "" {
					bodyMap["scheduleTimezone"] = bodyScheduleTimezone
				}
				if cmd.Flags().Changed("stop-on-response") {
					bodyMap["stopOnResponse"] = bodyStopOnResponse
				}
				if bodyTriggerConditions != "" {
					var parsedTriggerConditions any
					if err := json.Unmarshal([]byte(bodyTriggerConditions), &parsedTriggerConditions); err != nil {
						return fmt.Errorf("parsing --trigger-conditions JSON: %w", err)
					}
					bodyMap["triggerConditions"] = parsedTriggerConditions
				}
				if bodyTriggerEvent != "" {
					bodyMap["triggerEvent"] = bodyTriggerEvent
				}
			}
			data, statusCode, err := c.PatchWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "automations", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "automations", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "automations", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "automations", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "automations", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "automations",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "automations", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "automations", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyActions, "actions", "", "Linear array of actions (v1) or graph object (v2)")
	cmd.Flags().IntVar(&bodyCooldownDays, "cooldown-days", 0, "Cooldown days")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description")
	cmd.Flags().StringVar(&bodyExecutionTimezone, "execution-timezone", "", "Execution timezone")
	cmd.Flags().IntVar(&bodyExecutionWindowEnd, "execution-window-end", 0, "Hour (0-23) to stop executing")
	cmd.Flags().IntVar(&bodyExecutionWindowStart, "execution-window-start", 0, "Hour (0-23) to start executing")
	cmd.Flags().IntVar(&bodyGraphVersion, "graph-version", 1, "Graph version")
	cmd.Flags().BoolVar(&bodyIsActive, "is-active", true, "Is active")
	cmd.Flags().StringVar(&bodyKind, "kind", "n8n", "Kind")
	cmd.Flags().StringVar(&bodyN8nWebhookUrl, "n8n-webhook-url", "", "N8n webhook url")
	cmd.Flags().StringVar(&bodyN8nWorkflowId, "n8n-workflow-id", "", "N8n workflow id")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name")
	cmd.Flags().StringVar(&bodyReenrollmentRule, "reenrollment-rule", "every_time", "Reenrollment rule")
	cmd.Flags().StringVar(&bodySchedule, "schedule", "", "Cron expression (5-field, UTC) for scheduled automations")
	cmd.Flags().StringVar(&bodyScheduleTimezone, "schedule-timezone", "", "Schedule timezone")
	cmd.Flags().BoolVar(&bodyStopOnResponse, "stop-on-response", false, "Stop on response")
	cmd.Flags().StringVar(&bodyTriggerConditions, "trigger-conditions", "", "Trigger conditions")
	cmd.Flags().StringVar(&bodyTriggerEvent, "trigger-event", "", "Event that triggers this automation (e.g., contact.created, deal.stage_changed)")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
