// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConversationsComplianceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "compliance",
		Short:       "Get compliance for conversations",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConversationsComplianceGetConversationsContactIdCmd(flags))
	return cmd
}
