// Copyright 2026 conduyt. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/ptaramona/conduyt-crm-cli/internal/client"
	"github.com/ptaramona/conduyt-crm-cli/internal/store"
)

// isNetworkError returns true for errors caused by network connectivity issues
// (DNS, connection refused, timeout). HTTP 4xx/5xx errors are NOT network errors.
func isNetworkError(err error) bool {
	if err == nil {
		return false
	}
	var urlErr *url.Error
	if As(err, &urlErr) {
		// url.Error wraps the underlying network error
		err = urlErr.Err
	}
	var netErr *net.OpError
	if As(err, &netErr) {
		return true
	}
	var dnsErr *net.DNSError
	if As(err, &dnsErr) {
		return true
	}
	// Check for common network error strings
	msg := err.Error()
	return strings.Contains(msg, "connection refused") ||
		strings.Contains(msg, "no such host") ||
		strings.Contains(msg, "network is unreachable") ||
		strings.Contains(msg, "i/o timeout") ||
		strings.Contains(msg, "TLS handshake timeout")
}

// openStoreForRead opens the local SQLite store for reading.
// Returns nil, nil if the database file does not exist (no sync has been run).
func openStoreForRead(ctx context.Context, cliName string) (*store.Store, error) {
	dbPath := defaultDBPath(cliName)
	if _, err := os.Stat(dbPath); os.IsNotExist(err) {
		return nil, nil
	}
	return store.OpenWithContext(ctx, dbPath)
}

// scopedCachePath returns the path of the auto-mode write-through cache,
// namespaced by the client's (origin + effective-auth) fingerprint. This is
// SEPARATE from the explicit-sync store (defaultDBPath) so a different API key
// or origin can never read another's auto-cached rows: the filename itself
// differs. Empty scope (no client) falls back to a per-process-unusable name so
// nothing leaks into the shared store. See client.CacheScope.
func scopedCachePath(scope string) string {
	home, _ := os.UserHomeDir()
	if scope == "" {
		scope = "noscope"
	}
	return filepath.Join(home, ".local", "share", "conduyt-crm-pp-cli", "cache", "auto-"+scope+".db")
}

// openScopedCacheForRead opens the scoped auto-cache for reading. Returns nil,
// nil when the file does not exist (nothing auto-cached for this origin/key).
func openScopedCacheForRead(ctx context.Context, scope string) (*store.Store, error) {
	dbPath := scopedCachePath(scope)
	if _, err := os.Stat(dbPath); os.IsNotExist(err) {
		return nil, nil
	}
	return store.OpenWithContext(ctx, dbPath)
}

// localProvenance builds a DataProvenance for local data reads.
func localProvenance(db *store.Store, resourceType, reason string) DataProvenance {
	prov := DataProvenance{
		Source:       "local",
		Reason:       reason,
		ResourceType: resourceType,
	}
	_, lastSynced, _, err := db.GetSyncState(resourceType)
	if err == nil && !lastSynced.IsZero() {
		prov.SyncedAt = &lastSynced
	}
	return prov
}

func attachFreshness(prov DataProvenance, flags *rootFlags) DataProvenance {
	if flags != nil {
		prov.Freshness = flags.freshnessMeta
	}
	return prov
}

// resolveRead dispatches a GET request to either the live API or local store
// based on the --data-source flag. Returns the response data and provenance metadata.
//
// Parameters:
//   - c: the HTTP client for live API calls
//   - flags: root flags containing dataSource setting
//   - resourceType: the store resource type name (e.g., "links", "domains")
//   - isList: true for list endpoints, false for get-by-ID endpoints
//   - path: the API path (e.g., "/links" or "/links/abc123")
//   - params: query parameters for the API call
//   - headers: per-endpoint required headers (e.g. cal-api-version, Stripe-Version)
//     baked in by the command template at codegen time. Pass nil when the endpoint
//     declares no per-endpoint header overrides. Without this parameter, store-backed
//     reads on per-endpoint-versioned APIs silently get the wrong response shape
//     (cal-com retro #334 F1).
func resolveRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, isList bool, path string, params map[string]string, headers map[string]string) (json.RawMessage, DataProvenance, error) {
	switch flags.dataSource {
	case "local":
		data, prov, err := resolveLocal(ctx, resourceType, isList, path, params, "user_requested")
		return data, attachFreshness(prov, flags), err

	case "live":
		data, err := c.GetWithHeaders(path, params, headers)
		if err != nil {
			return nil, DataProvenance{}, err
		}
		return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil

	default: // "auto"
		// --no-cache forces live-only: never write-through, never fall back to a
		// persisted store. A network failure surfaces as an error rather than
		// silently serving any cached (and potentially cross-tenant) data.
		if flags.noCache {
			data, err := c.GetWithHeaders(path, params, headers)
			if err != nil {
				return nil, DataProvenance{}, err
			}
			return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil
		}
		scope := c.CacheScope()
		data, err := c.GetWithHeaders(path, params, headers)
		if err == nil {
			writeThroughCache(ctx, scope, resourceType, data)
			return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil
		}
		if !isNetworkError(err) {
			// HTTP 4xx/5xx errors propagate — not a fallback case
			return nil, DataProvenance{}, err
		}
		// Network error — fall back ONLY to this origin/key's scoped auto-cache,
		// never the shared sync store, so a DNS/timeout can't serve prior-tenant
		// rows written under a different key or origin.
		fallbackData, fallbackProv, fallbackErr := resolveScopedCache(ctx, scope, resourceType, isList, path, params, "api_unreachable")
		if fallbackErr != nil {
			return nil, DataProvenance{}, fmt.Errorf("API unreachable and no local data for this origin/key. Run 'conduyt-crm-pp-cli sync' to enable offline access.\n\nOriginal error: %w", err)
		}
		return fallbackData, attachFreshness(fallbackProv, flags), nil
	}
}

// resolvePaginatedRead dispatches a paginated GET request to either the live API
// or local store. When local, skips pagination and returns all synced data. The
// headers argument carries per-endpoint required headers; pass nil when the
// endpoint declares no overrides.
func resolvePaginatedRead(ctx context.Context, c *client.Client, flags *rootFlags, resourceType string, path string, params map[string]string, headers map[string]string, fetchAll bool, cursorParam, nextCursorPath, hasMoreField string) (json.RawMessage, DataProvenance, error) {
	switch flags.dataSource {
	case "local":
		data, prov, err := resolveLocal(ctx, resourceType, true, path, params, "user_requested")
		return data, attachFreshness(prov, flags), err

	case "live":
		data, err := paginatedGet(c, path, params, headers, fetchAll, cursorParam, nextCursorPath, hasMoreField)
		if err != nil {
			return nil, DataProvenance{}, err
		}
		return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil

	default: // "auto"
		// --no-cache forces live-only (see resolveRead for rationale).
		if flags.noCache {
			data, err := paginatedGet(c, path, params, headers, fetchAll, cursorParam, nextCursorPath, hasMoreField)
			if err != nil {
				return nil, DataProvenance{}, err
			}
			return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil
		}
		scope := c.CacheScope()
		data, err := paginatedGet(c, path, params, headers, fetchAll, cursorParam, nextCursorPath, hasMoreField)
		if err == nil {
			writeThroughCache(ctx, scope, resourceType, data)
			return data, attachFreshness(DataProvenance{Source: "live"}, flags), nil
		}
		if !isNetworkError(err) {
			return nil, DataProvenance{}, err
		}
		fallbackData, fallbackProv, fallbackErr := resolveScopedCache(ctx, scope, resourceType, true, path, params, "api_unreachable")
		if fallbackErr != nil {
			return nil, DataProvenance{}, fmt.Errorf("API unreachable and no local data for this origin/key. Run 'conduyt-crm-pp-cli sync' to enable offline access.\n\nOriginal error: %w", err)
		}
		return fallbackData, attachFreshness(fallbackProv, flags), nil
	}
}

// writeThroughCache upserts live API results into the per-origin/per-key SCOPED
// auto-cache (scopedCachePath) so an auto-mode network-error fallback can serve
// the same account's prior reads — and ONLY that account's. The scope namespaces
// the file by (origin + effective auth), so a different key/origin writes to a
// different file and can never read these rows back. Best-effort: failures are
// silently ignored (the live result already succeeded).
func writeThroughCache(ctx context.Context, scope string, resourceType string, data json.RawMessage) {
	db, err := store.OpenWithContext(ctx, scopedCachePath(scope))
	if err != nil {
		return
	}
	defer db.Close()

	// Collect items to upsert from various response shapes
	var items []json.RawMessage

	// Try direct array first
	if json.Unmarshal(data, &items) != nil || len(items) == 0 {
		items = nil
		// Try object — check for common envelope patterns (results, data, items)
		var envelope map[string]json.RawMessage
		if json.Unmarshal(data, &envelope) == nil {
			for _, key := range []string{"results", "data", "items"} {
				if raw, ok := envelope[key]; ok {
					var arr []json.RawMessage
					if json.Unmarshal(raw, &arr) == nil && len(arr) > 0 {
						items = arr
						break
					}
				}
			}
			// Single object with an id field (e.g., detail response)
			if items == nil {
				if _, ok := envelope["id"]; ok {
					_, _, _ = db.UpsertBatch(resourceType, []json.RawMessage{data})
					return
				}
			}
		}
	}

	if len(items) > 0 {
		_, _, _ = db.UpsertBatch(resourceType, items)
	}
}

// resolveLocal reads data from the local SQLite store.
// Note: local reads return ALL synced data for the resource type. Endpoint-specific
// filters (query params, path scoping like /teams/{id}/users) are NOT applied locally.
// The provenance metadata includes "unscoped":true when params were present but not applied.
func resolveLocal(ctx context.Context, resourceType string, isList bool, path string, params map[string]string, reason string) (json.RawMessage, DataProvenance, error) {
	db, err := openStoreForRead(ctx, "conduyt-crm-pp-cli")
	if err != nil {
		return nil, DataProvenance{}, fmt.Errorf("opening local database: %w\nRun 'conduyt-crm-pp-cli sync' first.", err)
	}
	if db == nil {
		return nil, DataProvenance{}, fmt.Errorf("no local data. Run 'conduyt-crm-pp-cli sync' first")
	}
	defer db.Close()
	return readStore(db, resourceType, isList, path, params, reason)
}

// resolveScopedCache reads from the auto-mode scoped cache (scopedCachePath),
// which is namespaced by the client's (origin + effective-auth) fingerprint.
// This is the ONLY persisted store the auto network-error fallback consults, so
// a fallback can never surface rows written under a different key or origin (the
// Finding-1 cross-tenant leak). Identical read semantics to resolveLocal.
func resolveScopedCache(ctx context.Context, scope string, resourceType string, isList bool, path string, params map[string]string, reason string) (json.RawMessage, DataProvenance, error) {
	db, err := openScopedCacheForRead(ctx, scope)
	if err != nil {
		return nil, DataProvenance{}, fmt.Errorf("opening local cache: %w", err)
	}
	if db == nil {
		return nil, DataProvenance{}, fmt.Errorf("no cached data for this origin/key")
	}
	defer db.Close()
	return readStore(db, resourceType, isList, path, params, reason)
}

// readStore performs the common list/get-by-id read against an already-open
// store and builds local provenance. Shared by resolveLocal (sync store) and
// resolveScopedCache (per-origin/key auto cache).
func readStore(db *store.Store, resourceType string, isList bool, path string, params map[string]string, reason string) (json.RawMessage, DataProvenance, error) {
	prov := localProvenance(db, resourceType, reason)

	// Warn if endpoint had filters that local reads can't reproduce
	if len(params) > 0 {
		fmt.Fprintf(os.Stderr, "warning: local data is unfiltered — endpoint filters are not applied to cached data\n")
	}

	if isList {
		raw, err := db.List(resourceType, 0) // 0 = no limit, return all synced data
		if err != nil {
			return nil, DataProvenance{}, fmt.Errorf("querying local store: %w", err)
		}
		// Filter out empty/invalid records (empty arrays, null, whitespace-only)
		// that can end up in the store from pagination boundary artifacts.
		var items []json.RawMessage
		for _, r := range raw {
			trimmed := strings.TrimSpace(string(r))
			if trimmed == "" || trimmed == "null" || trimmed == "[]" || trimmed == "{}" {
				continue
			}
			items = append(items, r)
		}
		if len(items) == 0 {
			return nil, DataProvenance{}, fmt.Errorf("no local data for %q. Run 'conduyt-crm-pp-cli sync' first", resourceType)
		}
		// Marshal []json.RawMessage into a single JSON array
		data, err := json.Marshal(items)
		if err != nil {
			return nil, DataProvenance{}, fmt.Errorf("marshaling local data: %w", err)
		}
		return data, prov, nil
	}

	// Get by ID — extract the last path segment as the ID
	parts := strings.Split(strings.TrimRight(path, "/"), "/")
	id := parts[len(parts)-1]

	item, err := db.Get(resourceType, id)
	if err != nil {
		return nil, DataProvenance{}, fmt.Errorf("querying local store: %w", err)
	}
	if item == nil {
		return nil, DataProvenance{}, fmt.Errorf("resource %q with ID %q not found in local store. Run 'conduyt-crm-pp-cli sync' first", resourceType, id)
	}
	return item, prov, nil
}

// Ensure time import is used (compilation guard).
var _ = time.Now
