// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func newExportCmd(flags *rootFlags) *cobra.Command {
	var format string
	var outputFile string
	var limit int
	var noCache bool

	cmd := &cobra.Command{
		Use:   "export <resource> [id]",
		Short: "Export data to JSONL or JSON for backup, migration, or analysis",
		Long: `Export paginated API data to a local file. Supports JSONL (one JSON object
per line, streaming-friendly) and JSON (array). JSONL is recommended for
large datasets as it has no memory pressure.`,
		Example: `  # Export all items as JSONL (streaming, recommended for large datasets)
  conduyt-crm-pp-cli export <resource> --format jsonl --output data.jsonl

  # Export with limit
  conduyt-crm-pp-cli export <resource> --format jsonl --limit 1000

  # Pipe to another tool
  conduyt-crm-pp-cli export <resource> --format jsonl | jq '.id'`,
		Args: cobra.MinimumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			validResources := map[string]bool{
				"accounts":              true,
				"activities":            true,
				"api-keys":              true,
				"appointments":          true,
				"automation-executions": true,
				"automations":           true,
				"availability":          true,
				"batch-operations":      true,
				"booking-pages":         true,
				"booking-routing-forms": true,
				"bulk":                  true,
				"calendars":             true,
				"calls":                 true,
				"companies":             true,
				"contacts":              true,
				"conversations":         true,
				"custom-fields":         true,
				"dashboard":             true,
				"deals":                 true,
				"dnc":                   true,
				"document-templates":    true,
				"drip-campaigns":        true,
				"drip-enrollments":      true,
				"drip-tracks":           true,
				"email-domains":         true,
				"emails":                true,
				"files":                 true,
				"forms":                 true,
				"generated-documents":   true,
				"groups":                true,
				"health":                true,
				"imports":               true,
				"integrations":          true,
				"invoices":              true,
				"lead-pool":             true,
				"lead-routing":          true,
				"messages":              true,
				"notes":                 true,
				"notifications":         true,
				"phone-numbers":         true,
				"pipelines":             true,
				"playbook-enrollments":  true,
				"playbooks":             true,
				"products":              true,
				"quick-connects":        true,
				"quick-notes":           true,
				"rep-shifts":            true,
				"saved-filters":         true,
				"scoring-rules":         true,
				"settings":              true,
				"smart-lists":           true,
				"smart-views":           true,
				"sms-providers":         true,
				"status-metadata":       true,
				"tags":                  true,
				"tasks":                 true,
				"up-for-grabs":          true,
				"users":                 true,
				"webhook-logs":          true,
				"webhooks":              true,
				"workflows":             true,
			}
			validResourceList := []string{
				"accounts",
				"activities",
				"api-keys",
				"appointments",
				"automation-executions",
				"automations",
				"availability",
				"batch-operations",
				"booking-pages",
				"booking-routing-forms",
				"bulk",
				"calendars",
				"calls",
				"companies",
				"contacts",
				"conversations",
				"custom-fields",
				"dashboard",
				"deals",
				"dnc",
				"document-templates",
				"drip-campaigns",
				"drip-enrollments",
				"drip-tracks",
				"email-domains",
				"emails",
				"files",
				"forms",
				"generated-documents",
				"groups",
				"health",
				"imports",
				"integrations",
				"invoices",
				"lead-pool",
				"lead-routing",
				"messages",
				"notes",
				"notifications",
				"phone-numbers",
				"pipelines",
				"playbook-enrollments",
				"playbooks",
				"products",
				"quick-connects",
				"quick-notes",
				"rep-shifts",
				"saved-filters",
				"scoring-rules",
				"settings",
				"smart-lists",
				"smart-views",
				"sms-providers",
				"status-metadata",
				"tags",
				"tasks",
				"up-for-grabs",
				"users",
				"webhook-logs",
				"webhooks",
				"workflows",
			}
			resource := args[0]
			if !validResources[resource] {
				return usageErr(fmt.Errorf("unknown resource %q; valid: %s", resource, strings.Join(validResourceList, ", ")))
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			if noCache {
				c.NoCache = true
			}

			path := "/" + resource
			if len(args) > 1 {
				path += "/" + args[1]
			}

			var writer *bufio.Writer
			if outputFile != "" {
				f, err := os.Create(outputFile)
				if err != nil {
					return fmt.Errorf("creating output file: %w", err)
				}
				defer f.Close()
				writer = bufio.NewWriter(f)
				defer writer.Flush()
			} else {
				writer = bufio.NewWriter(os.Stdout)
				defer writer.Flush()
			}

			data, err := c.Get(cmd.Context(), path, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}

			switch format {
			case "jsonl":
				var items []json.RawMessage
				if err := json.Unmarshal(data, &items); err != nil {
					fmt.Fprintln(writer, string(data))
					return nil
				}
				count := 0
				for _, item := range items {
					if limit > 0 && count >= limit {
						break
					}
					fmt.Fprintln(writer, string(item))
					count++
				}
				if outputFile != "" {
					fmt.Fprintf(os.Stderr, "Exported %d records to %s\n", count, outputFile)
				}
			default:
				enc := json.NewEncoder(writer)
				enc.SetIndent("", "  ")
				var parsed any
				if err := json.Unmarshal(data, &parsed); err != nil {
					return err
				}
				return enc.Encode(parsed)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&format, "format", "jsonl", "Output format: jsonl or json")
	cmd.Flags().StringVarP(&outputFile, "output", "o", "", "Output file path (default: stdout)")
	cmd.Flags().IntVar(&limit, "limit", 0, "Maximum records to export (0 = unlimited)")
	cmd.Flags().BoolVar(&noCache, "no-cache", false, "Bypass response cache for fresh data")

	return cmd
}
