// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMailboxCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "mailbox",
		Short:       "Get, create, and delete mailbox",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMailboxDeleteConnectionsIdCmd(flags))
	cmd.AddCommand(newMailboxGetCallbackMicrosoftCmd(flags))
	cmd.AddCommand(newMailboxGetConnectionsCmd(flags))
	cmd.AddCommand(newMailboxPostConnectMicrosoftCmd(flags))
	cmd.AddCommand(newMailboxPostWebhooksMicrosoftCmd(flags))
	return cmd
}
