// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newReportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "reports",
		Short:       "Pipeline, revenue, activity, team, and custom reports",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newReportsCreateCustomCmd(flags))
	cmd.AddCommand(newReportsDeleteCustomCmd(flags))
	cmd.AddCommand(newReportsGetActivityCmd(flags))
	cmd.AddCommand(newReportsGetBdaCmd(flags))
	cmd.AddCommand(newReportsGetCallsCmd(flags))
	cmd.AddCommand(newReportsGetCustomCmd(flags))
	cmd.AddCommand(newReportsGetDialerAgentHourlyCmd(flags))
	cmd.AddCommand(newReportsGetDialerAwardsCmd(flags))
	cmd.AddCommand(newReportsGetDialerDispositionsCmd(flags))
	cmd.AddCommand(newReportsGetDialerListPerformanceCmd(flags))
	cmd.AddCommand(newReportsGetEmailProvidersCmd(flags))
	cmd.AddCommand(newReportsGetEmailTemplatesCmd(flags))
	cmd.AddCommand(newReportsGetPipelineCmd(flags))
	cmd.AddCommand(newReportsGetRevenueCmd(flags))
	cmd.AddCommand(newReportsGetSmsDeliveryCmd(flags))
	cmd.AddCommand(newReportsGetSmsTemplatesCmd(flags))
	cmd.AddCommand(newReportsGetTeamCmd(flags))
	cmd.AddCommand(newReportsListCustomCmd(flags))
	cmd.AddCommand(newReportsPostCustomIdExportCmd(flags))
	cmd.AddCommand(newReportsPostCustomPreviewCmd(flags))
	cmd.AddCommand(newReportsRunCustomCmd(flags))
	cmd.AddCommand(newReportsUpdateCustomCmd(flags))
	return cmd
}
