// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSettingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "settings",
		Short:       "Account settings, branding, SMS/Twilio configuration",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSettingsDeleteAiByoCmd(flags))
	cmd.AddCommand(newSettingsDeleteWarmyCmd(flags))
	cmd.AddCommand(newSettingsGetCmd(flags))
	cmd.AddCommand(newSettingsGetAiCmd(flags))
	cmd.AddCommand(newSettingsGetBrandingCmd(flags))
	cmd.AddCommand(newSettingsGetDeliveryGuardCmd(flags))
	cmd.AddCommand(newSettingsGetDormancyCmd(flags))
	cmd.AddCommand(newSettingsGetLeadVisibilityCmd(flags))
	cmd.AddCommand(newSettingsGetSmsCmd(flags))
	cmd.AddCommand(newSettingsGetTwilioCmd(flags))
	cmd.AddCommand(newSettingsGetWarmyCmd(flags))
	cmd.AddCommand(newSettingsGetWarmyEngineCmd(flags))
	cmd.AddCommand(newSettingsPatchAiCmd(flags))
	cmd.AddCommand(newSettingsPatchDeliveryGuardCmd(flags))
	cmd.AddCommand(newSettingsPatchDormancyCmd(flags))
	cmd.AddCommand(newSettingsPatchLeadVisibilityCmd(flags))
	cmd.AddCommand(newSettingsPatchWarmyEngineCmd(flags))
	cmd.AddCommand(newSettingsPutAiByoCmd(flags))
	cmd.AddCommand(newSettingsPutWarmyCmd(flags))
	cmd.AddCommand(newSettingsTestIntegrationCmd(flags))
	cmd.AddCommand(newSettingsTestSmsCmd(flags))
	cmd.AddCommand(newSettingsTestTwilioCmd(flags))
	cmd.AddCommand(newSettingsUpdateCmd(flags))
	cmd.AddCommand(newSettingsUpdateBrandingCmd(flags))
	cmd.AddCommand(newSettingsUpdateSmsCmd(flags))
	cmd.AddCommand(newSettingsUpdateTwilioCmd(flags))
	return cmd
}
