// Copyright 2026 Paul Taramona and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSmartViewsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "smart-views",
		Short:       "List, create, update, and delete smart views",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSmartViewsDeleteIdCmd(flags))
	cmd.AddCommand(newSmartViewsListCmd(flags))
	cmd.AddCommand(newSmartViewsPatchIdCmd(flags))
	cmd.AddCommand(newSmartViewsPatchReorderCmd(flags))
	cmd.AddCommand(newSmartViewsPostCmd(flags))
	return cmd
}
