// Copyright 2026 conduyt. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Team member management and invitations",
	}

	cmd.AddCommand(newUsersGetCmd(flags))
	cmd.AddCommand(newUsersInviteCmd(flags))
	cmd.AddCommand(newUsersListCmd(flags))
	cmd.AddCommand(newUsersRemoveCmd(flags))
	cmd.AddCommand(newUsersUpdateCmd(flags))
	cmd.AddCommand(newUsersDeactivateCmd(flags))
	cmd.AddCommand(newUsersReactivateCmd(flags))
	return cmd
}
