// Copyright 2026 conduyt. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/ptaramona/conduyt-crm-cli/internal/cliutil"
	"github.com/ptaramona/conduyt-crm-cli/internal/config"
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"
	"time"
)

type Client struct {
	BaseURL    string
	Config     *config.Config
	HTTPClient *http.Client
	DryRun     bool
	// PATCH(upstream cli-printing-press#dryrun-mask-body): when false (default),
	// dry-run output masks the request body values instead of printing them
	// verbatim, so finance/customer PII never lands in terminal scrollback or
	// CI logs. Set via the --show-body flag for debugging.
	ShowBody bool
	// NoCache is retained for flag/call-site compatibility (the global
	// --no-cache flag binds to it, and several commands set it). It is now a
	// no-op: see the PATCH note on the cache removal below. GET reads ALWAYS hit
	// the API, so "bypass cache" is already the only behavior.
	NoCache bool
	limiter *cliutil.AdaptiveLimiter
}

// PATCH(upstream cli-printing-press#disable-persistent-get-cache):
//
// The persistent, cross-invocation on-disk GET cache (~/.cache/conduyt-crm-pp-cli)
// has been REMOVED. It was a performance optimization, not a feature, and it kept
// generating correctness edges round after round: to be safe the cache key had to
// reproduce — byte-for-byte — the exact Authorization credential AND target origin
// that net/http would transmit, across every auth source (env bearer, config
// headers, per-call overrides, case-variant duplicate header keys, URL userinfo,
// and redirect-injected userinfo) and every BaseURL (scheme/host/port/base-path).
// Any divergence between "what we fingerprinted" and "what the wire actually sent"
// is a cross-credential or cross-origin cache-poisoning bug.
//
// Proving that equivalence complete is fragile by construction. We prefer provable
// correctness over the optimization, so the persistent cache is gone entirely:
// reads always hit the live API. That deletes the whole class — there is no shared
// cache file two different credentials or origins can collide on, because there is
// no shared cache file at all. It also removes the moot auth-fingerprint machinery
// (cacheKey/authFingerprint/effectiveAuthorization/applyAuthSources/userinfo
// derivation) that existed only to scope that cache.
//
// The doctor NoCache fix, the response flattener, and all six original v1.1.3
// dogfood bug fixes work fully without the cache — none depended on it.

// APIError carries HTTP status information for structured exit codes.
type APIError struct {
	Method     string
	Path       string
	StatusCode int
	Body       string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("%s %s returned HTTP %d: %s", e.Method, e.Path, e.StatusCode, e.Body)
}

func newHTTPClient(timeout time.Duration, jar http.CookieJar) *http.Client {
	return &http.Client{
		Timeout:       timeout,
		Jar:           jar,
		CheckRedirect: secureRedirect,
	}
}

// secureRedirect runs before net/http sends each REDIRECTED request. It closes
// two credential-leak classes that the initial-request sanitization in do()
// cannot reach, because net/http follows redirects internally inside Do():
//
//  1. URL-userinfo Basic injection on redirects. If a Location URL carries
//     userinfo (https://attacker:creds@host/...), net/http would inject a Basic
//     Authorization header derived from it on the redirected request — an
//     Authorization we never computed. Clearing req.URL.User on every hop
//     disables that injection path for redirects exactly as do() disables it for
//     the initial request.
//
//  2. Authorization forwarding to a DIFFERENT host. net/http re-sends our
//     Authorization header across redirects; if a redirect points to another
//     host (origin), continuing to send the caller's bearer/Basic credential
//     leaks it to that host. We strip Authorization (and the cookie-bearing
//     headers net/http itself already strips on cross-host hops) whenever the
//     redirect target host differs from the previous request's host.
//
// net/http's own default CheckRedirect also caps the redirect chain at 10; we
// preserve that cap so this does not become an open-ended follow.
func secureRedirect(req *http.Request, via []*http.Request) error {
	if len(via) >= 10 {
		return fmt.Errorf("stopped after 10 redirects")
	}
	// Never let a Location URL's userinfo become a Basic Authorization header.
	req.URL.User = nil
	// Do not carry Authorization across an origin (host) change.
	if len(via) > 0 {
		prev := via[len(via)-1]
		if prev.URL != nil && !strings.EqualFold(req.URL.Host, prev.URL.Host) {
			req.Header.Del("Authorization")
		}
	}
	return nil
}

func New(cfg *config.Config, timeout time.Duration, rateLimit float64) *Client {
	httpClient := newHTTPClient(timeout, nil)
	return &Client{
		BaseURL:    strings.TrimRight(cfg.BaseURL, "/"),
		Config:     cfg,
		HTTPClient: httpClient,
		limiter:    cliutil.NewAdaptiveLimiter(rateLimit),
	}
}

// RateLimit returns the current effective rate limit in req/s. Returns 0 if disabled.
func (c *Client) RateLimit() float64 {
	return c.limiter.Rate()
}

func (c *Client) Get(path string, params map[string]string) (json.RawMessage, error) {
	return c.GetWithHeaders(path, params, nil)
}

// GetWithHeaders performs a GET against the live API. There is no persistent
// cache: reads always hit the server, which is what makes per-credential and
// per-origin correctness unconditional (see the cache-removal PATCH note above).
func (c *Client) GetWithHeaders(path string, params map[string]string, headers map[string]string) (json.RawMessage, error) {
	result, _, err := c.do("GET", path, params, nil, headers)
	return result, err
}

func (c *Client) ProbeGet(path string) (int, error) {
	_, status, err := c.do("GET", path, nil, nil, nil)
	return status, err
}

func (c *Client) Post(path string, body any) (json.RawMessage, int, error) {
	return c.do("POST", path, nil, body, nil)
}

func (c *Client) PostWithHeaders(path string, body any, headers map[string]string) (json.RawMessage, int, error) {
	return c.do("POST", path, nil, body, headers)
}

func (c *Client) Delete(path string) (json.RawMessage, int, error) {
	return c.do("DELETE", path, nil, nil, nil)
}

func (c *Client) DeleteWithHeaders(path string, headers map[string]string) (json.RawMessage, int, error) {
	return c.do("DELETE", path, nil, nil, headers)
}

func (c *Client) Put(path string, body any) (json.RawMessage, int, error) {
	return c.do("PUT", path, nil, body, nil)
}

func (c *Client) PutWithHeaders(path string, body any, headers map[string]string) (json.RawMessage, int, error) {
	return c.do("PUT", path, nil, body, headers)
}

func (c *Client) Patch(path string, body any) (json.RawMessage, int, error) {
	return c.do("PATCH", path, nil, body, nil)
}

func (c *Client) PatchWithHeaders(path string, body any, headers map[string]string) (json.RawMessage, int, error) {
	return c.do("PATCH", path, nil, body, headers)
}

// applyAuthorization writes the effective Authorization header onto h using do()'s
// precedence (later writes win): cfg.AuthHeader() < cfg.Headers["Authorization"] <
// headerOverrides["Authorization"]. Case-variant duplicate keys within a single
// source map ("Authorization" vs "authorization") are resolved deterministically
// (sorted by raw key, lexicographically-last variant wins) so the credential put
// on the wire never depends on Go's nondeterministic map iteration order. An
// explicitly-present empty Authorization is an explicit empty Set, not a fallback.
//
// This is the SOLE producer of the wire Authorization: do() strips req.URL.User
// before sending, so net/http cannot inject a URL-userinfo Basic header we did not
// write here.
func applyAuthorization(h http.Header, authHeader string, cfg *config.Config, headerOverrides map[string]string) {
	if authHeader != "" {
		h.Set("Authorization", authHeader)
	}
	if cfg != nil {
		setAuthDeterministic(h, cfg.Headers)
	}
	setAuthDeterministic(h, headerOverrides)
}

// setAuthDeterministic Sets the Authorization header from m, resolving
// case-variant duplicate keys ("Authorization" vs "authorization") in a stable
// order so the result does not depend on Go's nondeterministic map iteration.
// Variants are applied sorted by raw key; the lexicographically-last variant wins.
func setAuthDeterministic(h http.Header, m map[string]string) {
	variants := make([]string, 0)
	for k := range m {
		if strings.EqualFold(k, "Authorization") {
			variants = append(variants, k)
		}
	}
	if len(variants) == 0 {
		return
	}
	sort.Strings(variants)
	for _, k := range variants {
		h.Set("Authorization", m[k])
	}
}

// effectiveAuthorization computes the Authorization value do() will transmit,
// using applyAuthorization (the shared builder). Used by --dry-run to preview the
// exact credential without sending a request.
func effectiveAuthorization(authHeader string, cfg *config.Config, headerOverrides map[string]string) string {
	h := http.Header{}
	applyAuthorization(h, authHeader, cfg, headerOverrides)
	return h.Get("Authorization")
}

// do executes an HTTP request. headerOverrides, when non-nil, override global
// RequiredHeaders for this specific request (used for per-endpoint API versioning).
func (c *Client) do(method, path string, params map[string]string, body any, headerOverrides map[string]string) (json.RawMessage, int, error) {
	targetURL := c.BaseURL + path

	var bodyBytes []byte
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, 0, fmt.Errorf("marshaling body: %w", err)
		}
		bodyBytes = b
	}

	// Resolve auth material before the dry-run branch so --dry-run can preview
	// exactly what would be sent. Uses only cached credentials; a token that
	// requires a network refresh will be re-fetched on the live request path,
	// not during dry-run.
	authHeader, err := c.authHeader()
	if err != nil {
		return nil, 0, err
	}

	// Build the request for dry-run display or actual execution
	if c.DryRun {
		return c.dryRun(method, targetURL, path, params, bodyBytes, headerOverrides, authHeader)
	}

	const maxRetries = 3
	var lastErr error

	for attempt := 0; attempt <= maxRetries; attempt++ {
		// Proactive rate limiting — wait before sending
		c.limiter.Wait()
		var bodyReader io.Reader
		if bodyBytes != nil {
			bodyReader = strings.NewReader(string(bodyBytes))
		}

		req, err := http.NewRequest(method, targetURL, bodyReader)
		if err != nil {
			return nil, 0, fmt.Errorf("creating request: %w", err)
		}
		if bodyBytes != nil {
			req.Header.Set("Content-Type", "application/json")
		}

		if params != nil {
			q := req.URL.Query()
			for k, v := range params {
				if v != "" {
					q.Set(k, v)
				}
			}
			req.URL.RawQuery = q.Encode()
		}

		// Non-Authorization headers: apply config + overrides. Authorization keys
		// are skipped here and resolved through the shared applyAuthorization
		// helper below so the credential transmitted is deterministic.
		if c.Config != nil {
			for k, v := range c.Config.Headers {
				if strings.EqualFold(k, "Authorization") {
					continue
				}
				req.Header.Set(k, v)
			}
		}
		// Per-endpoint header overrides (e.g., different API version per resource)
		for k, v := range headerOverrides {
			if strings.EqualFold(k, "Authorization") {
				continue
			}
			req.Header.Set(k, v)
		}
		// Strip any userinfo from the request URL so net/http can NEVER inject an
		// Authorization header we did not compute. applyAuthorization below is the
		// sole producer of the wire Authorization. (Redirected requests are
		// sanitized separately by secureRedirect on the http.Client.)
		req.URL.User = nil
		// Authorization, resolved via the shared deterministic helper.
		applyAuthorization(req.Header, authHeader, c.Config, headerOverrides)
		if req.Header.Get("Authorization") == "" {
			req.Header.Del("Authorization")
		}
		if req.Header.Get("User-Agent") == "" {
			// PATCH: keep the default User-Agent aligned with the installed release.
			req.Header.Set("User-Agent", "github.com/ptaramona/conduyt-crm-cli/1.1.3")
		}

		resp, err := c.HTTPClient.Do(req)
		if err != nil {
			lastErr = fmt.Errorf("%s %s: %w", method, path, err)
			continue
		}

		respBody, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			return nil, 0, fmt.Errorf("reading response: %w", err)
		}
		respBody = sanitizeJSONResponse(respBody)

		// Success
		if resp.StatusCode < 400 {
			c.limiter.OnSuccess()
			return json.RawMessage(respBody), resp.StatusCode, nil
		}

		apiErr := &APIError{
			Method:     method,
			Path:       path,
			StatusCode: resp.StatusCode,
			Body:       truncateBody(respBody),
		}

		// Rate limited - adjust adaptive limiter and retry
		if resp.StatusCode == 429 && attempt < maxRetries {
			c.limiter.OnRateLimit()
			wait := cliutil.RetryAfter(resp)
			fmt.Fprintf(os.Stderr, "rate limited, waiting %s (attempt %d/%d, rate adjusted to %.1f req/s)\n", wait, attempt+1, maxRetries, c.limiter.Rate())
			time.Sleep(wait)
			lastErr = apiErr
			continue
		}

		// Server error - retry with backoff
		if resp.StatusCode >= 500 && attempt < maxRetries {
			wait := time.Duration(math.Pow(2, float64(attempt))) * time.Second
			fmt.Fprintf(os.Stderr, "server error %d, retrying in %s (attempt %d/%d)\n", resp.StatusCode, wait, attempt+1, maxRetries)
			time.Sleep(wait)
			lastErr = apiErr
			continue
		}

		// Client error or retries exhausted - return the error
		return nil, resp.StatusCode, apiErr
	}

	return nil, 0, lastErr
}

// dryRun prints the outgoing request exactly as the live path would send it,
// using the auth material already resolved in `do()`. Never triggers a network
// call — the caller is responsible for passing cached auth material only.
func (c *Client) dryRun(method, targetURL, path string, params map[string]string, body []byte, headerOverrides map[string]string, authHeader string) (json.RawMessage, int, error) {
	fmt.Fprintf(os.Stderr, "%s %s\n", method, targetURL)
	queryPrinted := false
	if params != nil {
		keys := make([]string, 0, len(params))
		for k := range params {
			if params[k] != "" {
				keys = append(keys, k)
			}
		}
		sort.Strings(keys)
		for _, k := range keys {
			sep := "?"
			if queryPrinted {
				sep = "&"
			}
			fmt.Fprintf(os.Stderr, "  %s%s=%s\n", sep, k, params[k])
			queryPrinted = true
		}
	}
	_ = queryPrinted
	if body != nil {
		// PATCH(upstream cli-printing-press#dryrun-mask-body): never print raw
		// request bodies by default — they routinely carry finance amounts,
		// customer PII, tokens, and notes. Print a masked structural preview
		// instead; --show-body opts into the full verbatim body for debugging.
		if c.ShowBody {
			var pretty json.RawMessage
			if json.Unmarshal(body, &pretty) == nil {
				enc := json.NewEncoder(os.Stderr)
				enc.SetIndent("  ", "  ")
				fmt.Fprintf(os.Stderr, "  Body:\n")
				_ = enc.Encode(pretty)
			}
		} else {
			masked := maskBodyForDryRun(body)
			enc := json.NewEncoder(os.Stderr)
			enc.SetIndent("  ", "  ")
			fmt.Fprintf(os.Stderr, "  Body (masked — use --show-body to reveal):\n")
			_ = enc.Encode(masked)
		}
	}
	// Preview the EXACT Authorization the live path would send (resolved through
	// the shared helper, so config/override Authorization — including case-variant
	// duplicates — is reflected, not just the bearer/AuthHeader value).
	if eff := effectiveAuthorization(authHeader, c.Config, headerOverrides); eff != "" {
		fmt.Fprintf(os.Stderr, "  %s: %s\n", "Authorization", maskToken(eff))
	}
	fmt.Fprintf(os.Stderr, "\n(dry run - no request sent)\n")
	return json.RawMessage(`{"dry_run": true}`), 0, nil
}

// PATCH(upstream cli-printing-press#dryrun-mask-body): maskBodyForDryRun
// returns a structural preview of a request body with all scalar values
// replaced by a redacted type marker. Keys are preserved so the caller can
// still verify the request shape (which fields are set) without exposing the
// underlying values. Nested objects and arrays are walked recursively.
func maskBodyForDryRun(body []byte) any {
	var parsed any
	if err := json.Unmarshal(body, &parsed); err != nil {
		return "«unparseable body redacted»"
	}
	return maskValue(parsed)
}

func maskValue(v any) any {
	switch t := v.(type) {
	case map[string]any:
		out := make(map[string]any, len(t))
		for k, val := range t {
			out[k] = maskValue(val)
		}
		return out
	case []any:
		out := make([]any, len(t))
		for i, val := range t {
			out[i] = maskValue(val)
		}
		return out
	case string:
		return "«string»"
	case float64:
		return "«number»"
	case bool:
		return "«bool»"
	case nil:
		return nil
	default:
		return "«value»"
	}
}

func (c *Client) ConfiguredTimeout() time.Duration {
	if c.HTTPClient != nil && c.HTTPClient.Timeout > 0 {
		return c.HTTPClient.Timeout
	}
	return 30 * time.Second
}

func (c *Client) authHeader() (string, error) {
	if c.Config == nil {
		return "", nil
	}
	if c.Config.AccessToken != "" && !c.Config.TokenExpiry.IsZero() && time.Now().After(c.Config.TokenExpiry) && c.Config.RefreshToken != "" {
		if err := c.refreshAccessToken(); err != nil {
			return "", err
		}
	}
	return c.Config.AuthHeader(), nil
}

func (c *Client) refreshAccessToken() error {
	if c.Config == nil {
		return nil
	}
	if c.Config.RefreshToken == "" {
		return nil
	}

	tokenURL := ""
	if tokenURL == "" {
		return nil
	}

	params := url.Values{
		"grant_type":    {"refresh_token"},
		"refresh_token": {c.Config.RefreshToken},
		"client_id":     {c.Config.ClientID},
	}
	if c.Config.ClientSecret != "" {
		params.Set("client_secret", c.Config.ClientSecret)
	}

	resp, err := c.HTTPClient.PostForm(tokenURL, params)
	if err != nil {
		return fmt.Errorf("refreshing access token: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("refreshing access token: HTTP %d: %s", resp.StatusCode, truncateBody(body))
	}

	var tokenResp struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
		ExpiresIn    int    `json:"expires_in"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return fmt.Errorf("parsing refresh response: %w", err)
	}
	if tokenResp.AccessToken == "" {
		return fmt.Errorf("refreshing access token: no access token in response")
	}

	refreshToken := c.Config.RefreshToken
	if tokenResp.RefreshToken != "" {
		refreshToken = tokenResp.RefreshToken
	}

	expiry := time.Time{}
	if tokenResp.ExpiresIn > 0 {
		expiry = time.Now().Add(time.Duration(tokenResp.ExpiresIn) * time.Second)
	}

	if err := c.Config.SaveTokens(c.Config.ClientID, c.Config.ClientSecret, tokenResp.AccessToken, refreshToken, expiry); err != nil {
		return fmt.Errorf("saving refreshed token: %w", err)
	}

	return nil
}

// sanitizeJSONResponse strips known JSONP/XSSI prefixes and UTF-8 BOM from
// response bodies so that downstream JSON parsing succeeds. For clean JSON
// responses these checks are no-ops.
func sanitizeJSONResponse(body []byte) []byte {
	// UTF-8 BOM
	body = bytes.TrimPrefix(body, []byte("\xEF\xBB\xBF"))

	// JSONP/XSSI prefixes, ordered longest-first where prefixes overlap
	prefixes := [][]byte{
		[]byte(")]}'\n"),
		[]byte(")]}'"),
		[]byte("{}&&"),
		[]byte("for(;;);"),
		[]byte("while(1);"),
	}
	for _, p := range prefixes {
		if bytes.HasPrefix(body, p) {
			body = bytes.TrimPrefix(body, p)
			body = bytes.TrimLeft(body, " \t\r\n")
			break
		}
	}
	return body
}

// maskToken redacts all but the last 4 characters of a token for safe display.
func maskToken(token string) string {
	if token == "" {
		return ""
	}
	if len(token) <= 4 {
		return "****"
	}
	return "****" + token[len(token)-4:]
}

func truncateBody(b []byte) string {
	s := string(b)
	if len(s) > 200 {
		return s[:200] + "..."
	}
	return s
}
